spaces=''*25
print(f'{spaces} 12 butts Wynd')
print (f'{spaces} Twinklebottom health')
print (f'{spaces} West snoring')
print ()
print()
print('Dear sir')
print()
print ('I wish to report that tiles are missing from the outside toilet roof')
print ('I think it was bad wind the other night that blew them away.')
print()
print ('regards')
print ('Malcolm Dithering')